export const queslists = [
  { id: 1, name: '비덕은 어떤 동물일까요?', url: './assets/image/1/1.jpg', url0: './assets/image/1/0.jpg', urlq: './assets/image/1/img.jpg', result: 1},
  { id: 2, name: '비덕의 색깔은?' , url: './assets/image/2/1.jpg', url0: './assets/image/2/0.jpg', urlq: './assets/image/2/img.jpg', result: 1},
  { id: 3, name: '비덕의 동생 이름은?', url: './assets/image/3/1.jpg', url0: './assets/image/3/0.jpg', urlq: './assets/image/3/img.jpg', result: 1},
  { id: 4, name: '진짜 비덕을 찾아주세요.', url: './assets/image/4/1.jpg', url0: './assets/image/4/0.jpg', urlq: './assets/image/4/img.jpg', result: 0},
  { id: 5, name: '비덕의 나이는?', url: './assets/image/5/1.jpg', url0: './assets/image/5/0.jpg', urlq: './assets/image/5/img.jpg', result: 1},
  { id: 6, name: '비덕의친구가 아닌 캐릭터는?', url: './assets/image/6/1.jpg', url0: './assets/image/6/0.jpg', urlq: './assets/image/6/img.jpg', result: 0},
  { id: 7, name: '다음 게임의 이름은 ㅇㅇㅇㅇㅇㅇ이다. ㅇ에들어갈 답은?', url: './assets/image/7/1.jpg', url0: './assets/image/7/0.jpg', urlq: './assets/image/7/img.jpg', result: 1},
  { id: 8, name: '다음 블록을 없애는 방법은?', url: './assets/image/8/1.jpg', url0: './assets/image/8/0.jpg', urlq: './assets/image/8/img.jpg', result: 0},
  { id: 9, name: '두게임의 캐릭터 이름은?', url: './assets/image/9/1.jpg', url0: './assets/image/9/0.jpg', urlq: './assets/image/9/img.jpg', result: 1},
  { id: 10, name: '비덕 막냇동생의 이름은?', url: './assets/image/10/1.jpg', url0: './assets/image/10/0.jpg', urlq: './assets/image/10/img.jpg', result: 1},
  { id: 11, name: '버피가 유학을 갔던나라는?', url: './assets/image/11/1.jpg', url0: './assets/image/11/0.jpg', urlq: './assets/image/11/img.jpg', result: 1},
  { id: 12, name: '비덕이 가장 좋아하는 간식은?',  url: './assets/image/12/1.jpg', url0: './assets/image/12/0.jpg', urlq: './assets/image/12/img.jpg', result: 1},
  { id: 13, name: '비덕 여자친구의 이름은?', url: './assets/image/13/1.jpg', url0: './assets/image/13/0.jpg', urlq: './assets/image/13/img.jpg',  result: 1},
  { id: 14, name: '버피가 가장 좋아하는 악세서리는?', url: './assets/image/14/1.jpg', url0: './assets/image/14/0.jpg', urlq: './assets/image/14/img.jpg', result: 1},
  { id: 15, name: 'TEAL이 노란색에서 파란색으로 변한 이유는?', url: './assets/image/15/1.jpg', url0: './assets/image/15/0.jpg', urlq: './assets/image/15/img.jpg', result: 1},
  { id: 16, name: 'FROGGY가 좋아하는 운동은?', url: './assets/image/16/1.jpg', url0: './assets/image/16/0.jpg', urlq: './assets/image/16/img.jpg', result: 1},
  { id: 17, name: '비덕과 버피의 엄마인 MAMA가 가장 잘하는 것은?', url: './assets/image/17/1.jpg', url0: './assets/image/17/0.jpg', urlq: './assets/image/17/img.jpg', result: 1},
  { id: 18, name: 'RICE의 꿈은 과학자이다.', url: './assets/image/18/1.jpg', url0: './assets/image/18/0.jpg', urlq: './assets/image/18/img.jpg', result: 1},
  { id: 19, name: 'TEAL의 동생은?', url: './assets/image/19/1.jpg', url0: './assets/image/19/0.jpg', urlq: './assets/image/19/img.jpg', result: 1},
  { id: 20, name: '비덕 베이비의 나이는?', url: './assets/image/20/1.jpg', url0: './assets/image/20/0.jpg', urlq: './assets/image/20/img.jpg', result: 1},
 ];