export const queslists = [
  { id: 1, name: '비덕은 어떤 동물일까요?', url: 'url', result: 1},
  { id: 2, name: '비덕의 색깔은?' , url: 'url', result: 1},
  { id: 3, name: '비덕의 동생 이름은?', url: 'url',  result: 1},
  { id: 4, name: '진짜 비덕을 찾아주세요.', url: 'url', result: 0},
  { id: 5, name: '비덕의 나이는?', url: 'url', result: 1},
  { id: 6, name: '비덕의친구가 아닌 캐릭터는?', url: 'url', result: 0},
  { id: 7, name: '다음 게임의 이름은 ㅇㅇㅇㅇㅇㅇ이다. ㅇ에들어갈 답은?', url: 'url', result: 1},
  { id: 8, name: '다음 블록을 없애는 방법은?', url: 'url', result: 0},
  { id: 9, name: '두게임의 캐릭터 이름은?', url: 'url', result: 1},
  { id: 10, name: '비덕 막냇동생의 이름은?', url: 'url', result: 1},
  { id: 11, name: '버피가 유학을 갔던나라는?', url: 'url', result: 1},
  { id: 12, name: '비덕이 가장 좋아하는 간식은?',  url: 'url', result: 1},
  { id: 13, name: '비덕 여자친구의 이름은?', url: 'url',  result: 1},
  { id: 14, name: '버피가 가장 좋아하는 악세서리는?', url: 'url', result: 1},
  { id: 15, name: 'TEAL이 노란색에서 파란새으로 변한 이유는?', url: 'url', result: 1},
  { id: 16, name: 'FROGGY가 좋아하는 운동은?', url: 'url', result: 1},
  { id: 17, name: '비덕과 버피의 엄마인 MAMA가 가장 잘하는 것은?', url: 'url', result: 1},
  { id: 18, name: 'RICE의 꿈은 과학자이다.', url: 'url', result: 1},
  { id: 19, name: 'TEAL의 동생은?', url: 'url', result: 1},
  { id: 20, name: '비덕 베이비의 나이는?', url: 'url', result: 1},
];
